server:
  servlet:
    session:
      timeout: 30
  port: 9091

spring:
  application:
    name: baseProject
  session:
    store-type: jdbc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://192.168.11.248:3306/demo?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml,classpath:mybatis/**/*.xml
  configuration:
    call-setters-on-nulls: true

logging:
  config: classpath:logback.xml

swagger:
  show:true

#1 是开启前者顶掉否则,0 是多者登录 old
isConcurrent: 0

#错误次数配置  old
wrongCounts: 3

upload-path: E:/jintan-service/upload